# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f3f69e869a0d753b5cca0f19d18353404bdbbe650857a0b562e4894ccaefc6eb0e6aa985f6a82b86318f139ae2cb4672e86b322796893296972f59894fb0b9

test:
  secret_key_base: 48e6a17adb3cf94a9f96d2672cd80fa596c2d8603bdd0c14aa974a94ef0fdb118a31f1bd4bf1c366bf22e72dcab9254880e340fc7bb0fdc670e09ab38e63247a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
